name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1  
      with:       
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: elli31/labdevops       
        tags: ${{ github.run_number }}
    - name: Add and print logs using Log4j
      run: |
        mkdir -p src/main/resources
        echo "log4j.rootLogger=INFO, stdout" > src/main/resources/log4j2.properties
        echo "log4j.appender.stdout=org.apache.log4j.ConsoleAppender" >> src/main/resources/log4j2.properties
        echo "log4j.appender.stdout.Target=System.out" >> src/main/resources/log4j2.properties
        echo "log4j.appender.stdout.layout=org.apache.log4j.PatternLayout" >> src/main/resources/log4j2.properties
        echo "log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n" >> src/main/resources/log4j2.properties
        mvn clean package -DskipTests
